### ISSUE TITLE
`statistics.min_value` is `undefined` instead of `''`

### ISSUE THREAD

**Issue by severo** [hyparam/hyparquet#10]
It's not an important thing, but I found that for some parquet files, the `statistics.min_value` is `undefined` when the raw value is an empty string.

See the file https://huggingface.co/datasets/CohereForAI/aya_dataset/blob/main/data/train-00000-of-00001.parquet:

On https://huggingface.co/datasets/CohereForAI/aya_dataset/tree/main/data?show_file_info=data%2Ftrain-00000-of-00001.parquet
<img width="667" alt="Capture d’écran 2024-05-14 à 14 02 34" src="https://github.com/hyparam/hyparquet/assets/1676121/9169e2dc-847b-4eed-82ba-5edb0fa67949">

```js
>> metadata.row_groups[0].columns[0].meta_data.statistics 
{ 
	distinct_count: undefined
	is_max_value_exact: undefined,
	is_min_value_exact: undefined,
	max: undefined,
	max_value: "🇰🇬 Манас эпосу 📚\nАты да Манас турбайбы, заты да Манас турбайбы.\nӨзү да Манас турбайбы, сөзү да Манас турбайбы.\nАлмамбет болсо жолдошум, кан Манас болсо жолборсум.\nКасташкан жоодон жалтансам, мени кудай урбайбы, - деп зор дем менен жоого каршы аттанган баатыр\n\nа) Алмамбет \nб) Сыргак\nв) Чубак \nг) Серек\n\n",
	min: undefined,
	min_value: undefined,
	null_count: 0n
}
```

On https://hyparam.github.io/hyparquet/
<img width="289" alt="Capture d’écran 2024-05-14 à 14 03 00" src="https://github.com/hyparam/hyparquet/assets/1676121/d21bfeeb-a494-4d01-a2a7-1dda40139684">

With pyarrow.parquet:

```python
>>> from pyarrow import parquet
>>> parquet.read_metadata("train-00000-of-00001.parquet").row_group(0).column(0).statistics
<pyarrow._parquet.Statistics object at 0x7cb3d3f39a40>
  has_min_max: True
  min:
  max: 🇰🇬 Манас эпосу 📚
Аты да Манас турбайбы, заты да Манас турбайбы.
Өзү да Манас турбайбы, сөзү да Манас турбайбы.
Алмамбет болсо жолдошум, кан Манас болсо жолборсум.
Касташкан жоодон жалтансам, мени кудай урбайбы, - деп зор дем менен жоого каршы аттанган баатыр

а) Алмамбет
б) Сыргак
в) Чубак
г) Серек


  null_count: 0
  distinct_count: None
  num_values: 1000
  physical_type: BYTE_ARRAY
  logical_type: String
  converted_type (legacy): UTF8
>>> parquet.read_metadata("train-00000-of-00001.parquet").row_group(0).column(0).statistics.min
''
```

**Comment by platypii** [comment]
After some investigation, I believe that hyparquet is correctly parsing the file. Details:

Parquet metadata is written as thrift serialized data according to [parquet.thrift](https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L276-L277). This particular parquet file has a `max_value` but no `min_value` defined in the thrift data.

Arrow and duckdb print `undefined` statistics as empty string. But in reality, the min value is not empty string. If you look at the data, there are no empty rows, and the real min for this row group is `\nHint: \nఅరుణాచలం లేదా "అన్నామలై" తమిళనాడు రాష్ట్రములో ఉంది. అరుణాచలం పంచభూతలింగ క్షేత్రాలలో ఒకటి...` But there’s no way to know that from the metadata, only by looking at the values.

![issue10-duckdb-select](https://github.com/hyparam/hyparquet/assets/1766297/97f47ede-712c-4ba1-9693-8ece213a4bd6)

Why does pyarrow write undefined `min_value`? Because the the true min value is over 4k bytes, and large values get cleared (not truncated) when writing the parquet file using arrow [[1]](https://github.com/apache/arrow/blob/apache-arrow-16.1.0/cpp/src/parquet/properties.h#L143) [[2]](https://github.com/apache/arrow/blob/apache-arrow-16.1.0/cpp/src/parquet/statistics.h#L145-L159).

So I think undefined `min_value` is the right behavior here. But I am open to suggestions on better behavior. Thanks for reporting @severo!

**Comment by severo** [comment]
wow, thanks for this in-depth investigation and answer!

cc @julien_c @lhoestq @AndreaFrancis @polinaeterna for visibility: did you know that

> Because the the true min value is over 4k bytes, and large values get cleared (not truncated) when writing the parquet file using arrow

Not sure if we want another behavior to be honest.
